
import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Image, TextInput, Alert, ActivityIndicator } from 'react-native';
import { Github, Plus, ChevronLeft, LogOut, Package, ExternalLink, GitBranch, Terminal } from 'lucide-react-native';
import { useGitHubStore } from '../store/githubStore';
import { useGameStore } from '../store';
import { githubService } from '../services/githubService';
import { COLORS } from '../constants';

export default function GitHubScreen() {
  const { setView } = useGameStore();
  const { accessToken, user, repos, setToken, setUser, setRepos, logout } = useGitHubStore();
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [newRepoName, setNewRepoName] = useState('');
  const [showCreate, setShowCreate] = useState(false);

  const loadGitHubData = async (token: string) => {
    setIsRefreshing(true);
    try {
      const [userData, repoData] = await Promise.all([
        githubService.getUser(token),
        githubService.listRepos(token)
      ]);
      setUser(userData);
      setRepos(repoData);
    } catch (e) {
      Alert.alert('Error', 'Failed to connect to GitHub. Please check your token.');
      setToken(null);
    } finally {
      setIsRefreshing(false);
    }
  };

  const handleConnect = () => {
    Alert.prompt(
      "GitHub Personal Access Token",
      "Please enter a token with 'repo' scope from your GitHub Developer Settings.",
      [
        { text: "Cancel", style: "cancel" },
        { 
          text: "Connect", 
          onPress: (token) => {
            if (token) {
              setToken(token);
              loadGitHubData(token);
            }
          } 
        }
      ]
    );
  };

  const handleCreateRepo = async () => {
    if (!newRepoName || !accessToken) return;
    setIsRefreshing(true);
    try {
      await githubService.createRepo(accessToken, newRepoName, "Generated by Piano Tiles Pro");
      Alert.alert('Success', 'Repository created successfully!');
      loadGitHubData(accessToken);
      setShowCreate(false);
      setNewRepoName('');
    } catch (e: any) {
      Alert.alert('Error', e.message);
    } finally {
      setIsRefreshing(false);
    }
  };

  useEffect(() => {
    if (accessToken && !user) {
      loadGitHubData(accessToken);
    }
  }, []);

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => setView('MENU')} style={styles.backBtn}>
          <ChevronLeft color="#fff" size={24} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>GitHub Integration</Text>
        {user && (
          <TouchableOpacity onPress={logout} style={styles.logoutBtn}>
            <LogOut color="#ff5555" size={20} />
          </TouchableOpacity>
        )}
      </View>

      {!accessToken ? (
        <View style={styles.emptyContainer}>
          <Github color={COLORS.primary} size={80} style={styles.emptyIcon} />
          <Text style={styles.emptyTitle}>Store Your Code</Text>
          <Text style={styles.emptyText}>Connect your GitHub account to export generated C++ game logic directly to your repositories.</Text>
          <TouchableOpacity style={styles.connectBtn} onPress={handleConnect}>
            <Github color="#000" size={20} />
            <Text style={styles.connectBtnText}>CONNECT WITH GITHUB</Text>
          </TouchableOpacity>
        </View>
      ) : (
        <ScrollView style={styles.content}>
          {user && (
            <View style={styles.profileCard}>
              <Image source={{ uri: user.avatar_url }} style={styles.avatar} />
              <View>
                <Text style={styles.userName}>{user.name || user.login}</Text>
                <Text style={styles.userLogin}>@{user.login}</Text>
                <View style={styles.badge}>
                  <Package size={12} color={COLORS.primary} />
                  <Text style={styles.badgeText}>{user.public_repos} Repositories</Text>
                </View>
              </View>
            </View>
          )}

          <View style={styles.sectionHeader}>
            <Text style={styles.sectionTitle}>Your Repositories</Text>
            <TouchableOpacity onPress={() => setShowCreate(!showCreate)} style={styles.addBtn}>
              <Plus color={COLORS.primary} size={20} />
            </TouchableOpacity>
          </View>

          {showCreate && (
            <View style={styles.createBox}>
              <TextInput 
                style={styles.input}
                placeholder="Repository Name"
                placeholderTextColor="#666"
                value={newRepoName}
                onChangeText={setNewRepoName}
              />
              <TouchableOpacity style={styles.createBtn} onPress={handleCreateRepo}>
                {isRefreshing ? <ActivityIndicator color="#000" /> : <Text style={styles.createBtnText}>CREATE REPO</Text>}
              </TouchableOpacity>
            </View>
          )}

          {repos.map(repo => (
            <View key={repo.id} style={styles.repoCard}>
              <View style={styles.repoHeader}>
                <Package size={18} color={COLORS.primary} />
                <Text style={styles.repoName}>{repo.name}</Text>
                {repo.private && <View style={styles.privateTag}><Text style={styles.privateText}>PRIVATE</Text></View>}
              </View>
              <Text style={styles.repoDesc} numberOfLines={2}>{repo.description || 'No description provided.'}</Text>
              <View style={styles.repoFooter}>
                <View style={styles.repoStat}>
                  <GitBranch size={14} color="#666" />
                  <Text style={styles.repoStatText}>main</Text>
                </View>
                <TouchableOpacity style={styles.viewBtn}>
                  <ExternalLink size={14} color={COLORS.primary} />
                  <Text style={styles.viewBtnText}>VIEW ON GITHUB</Text>
                </TouchableOpacity>
              </View>
            </View>
          ))}
        </ScrollView>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  header: { 
    height: 100, 
    paddingTop: 40, 
    flexDirection: 'row', 
    alignItems: 'center', 
    justifyContent: 'space-between', 
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)'
  },
  backBtn: { padding: 8 },
  headerTitle: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  logoutBtn: { padding: 8 },
  content: { flex: 1, padding: 20 },
  emptyContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 40 },
  emptyIcon: { marginBottom: 24, opacity: 0.5 },
  emptyTitle: { color: '#fff', fontSize: 24, fontWeight: 'bold', marginBottom: 12 },
  emptyText: { color: '#888', textAlign: 'center', lineHeight: 22, marginBottom: 32 },
  connectBtn: { 
    backgroundColor: COLORS.primary, 
    flexDirection: 'row', 
    alignItems: 'center', 
    paddingHorizontal: 24, 
    paddingVertical: 16, 
    borderRadius: 30,
    gap: 10
  },
  connectBtnText: { color: '#000', fontWeight: 'bold', letterSpacing: 1 },
  profileCard: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    backgroundColor: '#1a1410', 
    padding: 20, 
    borderRadius: 24,
    gap: 16,
    marginBottom: 30,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.05)'
  },
  avatar: { width: 60, height: 60, borderRadius: 30, backgroundColor: '#333' },
  userName: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  userLogin: { color: '#666', fontSize: 14, marginBottom: 6 },
  badge: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  badgeText: { color: COLORS.primary, fontSize: 12, fontWeight: 'bold' },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
  sectionTitle: { color: '#fff', fontSize: 14, fontWeight: 'bold', letterSpacing: 2, opacity: 0.5 },
  addBtn: { padding: 4 },
  createBox: { backgroundColor: '#1a1410', padding: 16, borderRadius: 16, marginBottom: 20 },
  input: { color: '#fff', height: 45, borderBottomWidth: 1, borderBottomColor: '#333', marginBottom: 16 },
  createBtn: { backgroundColor: COLORS.primary, height: 45, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  createBtnText: { color: '#000', fontWeight: 'bold' },
  repoCard: { 
    backgroundColor: '#1a1410', 
    padding: 20, 
    borderRadius: 20, 
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.03)'
  },
  repoHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  repoName: { color: '#fff', fontSize: 16, fontWeight: 'bold', flex: 1 },
  privateTag: { backgroundColor: '#333', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 },
  privateText: { color: '#888', fontSize: 8, fontWeight: 'bold' },
  repoDesc: { color: '#888', fontSize: 12, lineHeight: 18, marginBottom: 16 },
  repoFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  repoStat: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  repoStatText: { color: '#666', fontSize: 12 },
  viewBtn: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  viewBtnText: { color: COLORS.primary, fontSize: 12, fontWeight: 'bold' }
});
